//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurHouseApps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDNAppsEntities : DbContext
    {
        public SDNAppsEntities()
            : base("name=SDNAppsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionCategory> ActionCategories { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<BabyName> BabyNames { get; set; }
        public virtual DbSet<LiquidSize> LiquidSizes { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<ReminderType> ReminderTypes { get; set; }
        public virtual DbSet<ThingsDone> ThingsDones { get; set; }
    }
}
